// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bd81cfe6-8973-4437-bc9f-ec9fd9df7bc4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Gs1mVlE0f",
    "aws_user_pools_web_client_id": "3io6r2cm9tklm5vqpt1cacv2l4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jugv6p3exbc2xbcyhrebioaxqe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dffsyywltrehpodi4b3uo2ty5a",
    "aws_content_delivery_bucket": "angular-blog-20190804203426-hostingbucket-master",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2q1imbo3fxqo3.cloudfront.net"
};


export default awsmobile;
